name: acceptance-test

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      # Need to checkout for testing the Action in this repo
      - uses: actions/checkout@v3

      - uses: ./
        id: json-yaml-validate
        with:
            exclude_file: __tests__/fixtures/exclude/exclude.txt
